const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
let xml;try{xml=require('xml-js')}catch{xml=require('/opt/codex/runtimes/codex-primary-runtime/dependencies/node/node_modules/xml-js');}
class XMLNode{constructor(n){this.n=n;}getAttribute(k){return this.n.attributes?.[k]??null;}get textContent(){return this.n.type==='text'?this.n.text:(this.n.elements||[]).map(n=>new XMLNode(n).textContent).join('');}getElementsByTagName(name){const result=[];for(const c of this.n.elements||[]){if(c.name===name)result.push(new XMLNode(c));result.push(...new XMLNode(c).getElementsByTagName(name));}return result;}querySelector(s){return this.getElementsByTagName(s)[0]||null;}}
class DOMParser{parseFromString(s){return new XMLNode(xml.xml2js(s));}}
const context=vm.createContext({console,TextDecoder,Uint8Array,DataView,Date,DOMParser,Blob,DecompressionStream});vm.runInContext(fs.readFileSync(path.join(__dirname,'../v2/parser.js'),'utf8')+'\n globalThis.core={parseCSV,normalizeDate,toCents,importRows,readXLSX,validateRecord};',context);const c=context.core;
assert.equal(c.toCents('￥1,234.56'),123456);assert.equal(c.toCents('0.01'),1);assert.equal(c.toCents('1.999'),null);assert.equal(c.toCents('-1'),null);assert.equal(c.toCents('Infinity'),null);
assert.equal(c.normalizeDate('2026/9/18 2:03:04'),'2026-09-18 02:03:04');assert.equal(c.normalizeDate('2026-02-30'),null);assert.equal(c.normalizeDate('2026-09-18 25:00'),null);
const wx='微信支付账单明细\n交易时间,交易类型,交易对方,商品,收/支,金额(元),支付方式,当前状态,交易单号,商户单号,备注\n2026-09-18 12:30:00,商户消费,食堂,"午饭,加蛋",支出,￥12.30,零钱,支付成功,wx001,m1,/\n2026-09-18 12:40:00,退款,食堂,退菜,收入,2.00,零钱,退款成功,wx002,m2,/\n2026-09-18 12:41:00,转账,自己,转入,/,100.00,零钱,转账成功,wx003,m3,/\n2026-09-18 12:42:00,商户消费,商场,衣服,支出,200.00,零钱,交易关闭,wx004,m4,/\n不合法,商户消费,食堂,午饭,支出,3.00,零钱,支付成功,wx005,m5,/';
const p=c.importRows(c.parseCSV(wx),'微信账单.csv');assert.equal(p.source,'微信');assert.equal(p.records.length,4);assert.equal(p.records[0].amount,1230);assert.equal(p.records[0].payment,'零钱');assert.equal(p.records[0].raw.kind,'商户消费');assert.equal(p.records[0].note,'午饭,加蛋');assert.equal(p.records[0].category,'餐饮美食');assert.equal(p.records[1].type,'refund');assert.equal(p.records[2].type,'neutral');assert.equal(p.ignored,0);
assert.equal(p.records[3].type,'neutral');assert.equal(p.records[0].recognition.eventType,'expense');assert.equal(p.records[1].recognition.eventType,'refund');assert.equal(p.records[1].recognition.flow.toLabel,'微信零钱');assert.equal(p.records[2].recognition.eventType,'transfer');assert.equal(p.records[2].recognition.symbols.slash,'column_placeholder');
assert.equal(p.records[3].status,'交易关闭');assert.equal(p.rejected,1);
const ali='交易时间,交易分类,交易对方,交易对方账号,商品说明,收/支,金额,收/付款方式,交易状态,交易订单号,商家订单号,备注\n2026-09-17 18:00:00,交通出行,地铁,x,车票,支出,6.00,余额,交易成功,ali001,m1,/';const a=c.importRows(c.parseCSV(ali),'账单.csv');assert.equal(a.source,'支付宝');assert.equal(a.records[0].amount,600);assert.equal(a.records[0].category,'交通出行');assert.equal(new Set([...p.records,...c.importRows(c.parseCSV(wx),'账单.csv').records].map(r=>r.id)).size,4);
const special=c.importRows(c.parseCSV('交易时间,交易分类,交易对方,对方账号,商品说明,收/支,金额,收/付款方式,交易状态,交易订单号,商家订单号,备注\n2026-09-18 10:00:00,餐饮美食,店铺,x,退款-早餐,不计收支,0.35,亲情卡(妈妈),退款成功,refund-1,m-1,\n2026-09-18 11:00:00,服饰装扮,店铺,x,裤子,支出,200.00,花呗,交易成功,ali-credit,m-2,'), '支付宝账单.csv');assert.equal(special.records[0].type,'refund');assert.equal(special.records[0].payerType,'family-card');assert.equal(special.records[1].payerType,'huabei-history');assert.throws(()=>c.parseCSV('a,"unfinished'));assert.throws(()=>c.importRows([['unknown']],'x'));assert.throws(()=>c.validateRecord({...p.records[0],amount:1.25}));assert.throws(()=>c.validateRecord({...p.records[0],type:'not-a-type'}));assert.equal(c.validateRecord(p.records[0]).amount,1230);
const familyPurchase=c.importRows(c.parseCSV('交易时间,交易分类,交易对方,对方账号,商品说明,收/支,金额,收/付款方式,交易状态,交易订单号,商家订单号,备注\n2026-09-18 10:30:00,餐饮美食,店铺,x,早餐,不计收支,20.00,亲情卡(妈妈),交易成功,family-1,m-5,'),'支付宝账单.csv');assert.equal(familyPurchase.records[0].type,'expense');assert.equal(familyPurchase.records[0].payerType,'family-card');assert.equal(familyPurchase.records[0].recognition.eventType,'expense');assert.equal(familyPurchase.records[0].recognition.flow.fromType,'external_payer');
const instruments=c.importRows(c.parseCSV('交易时间,交易分类,交易对方,对方账号,商品说明,收/支,金额,收/付款方式,交易状态,交易订单号,商家订单号,备注\n2026-09-18 12:00:00,消费,店铺,x,商品,支出,100.00,招商银行储蓄卡(1234)&红包,交易成功,same-order,m-3,\n2026-09-18 13:00:00,信用借还,花呗,x,花呗还款,支出,80.00,建设银行储蓄卡(5678),交易成功,repay-1,m-4,'),'支付宝账单.csv');assert.equal(instruments.records[0].paymentKey,'招商银行储蓄卡(1234)');assert.deepEqual(Array.from(instruments.records[0].paymentParts),['招商银行储蓄卡(1234)','红包']);assert.equal(instruments.records[1].type,'neutral');assert.equal(instruments.records[1].payerType,'huabei-repayment-history');
const changedStatus=c.importRows(c.parseCSV('交易时间,交易分类,交易对方,对方账号,商品说明,收/支,金额,收/付款方式,交易状态,交易订单号,商家订单号,备注\n2026-09-18 12:00:00,消费,店铺,x,商品,不计收支,100.00,招商银行储蓄卡(1234),交易关闭,same-order,m-3,'),'支付宝账单.csv');assert.equal(instruments.records[0].id,changedStatus.records[0].id);
const wxTransfers=c.importRows(c.parseCSV('交易时间,交易类型,交易对方,商品,收/支,金额(元),支付方式,当前状态,交易单号,商户单号,备注\n2026-09-18 12:00:00,转账,对象,转账备注:取回存款,收入,200.00,/,已存入零钱,in-1,/,/\n2026-09-18 13:00:00,转账,公寓,转账备注:押金,支出,200.00,零钱,对方已退还,out-1,m-out,/\n2026-09-18 14:00:00,转账-退款,/,转账备注:押金,收入,200.00,零钱,已全额退款,refund-out-1,,/'),'微信账单.csv');assert.equal(wxTransfers.records[0].recognition.eventType,'transfer');assert.equal(wxTransfers.records[0].recognition.platformDirection.code,'in');assert.equal(wxTransfers.records[0].recognition.flow.fromLabel,'对象');assert.equal(wxTransfers.records[0].recognition.flow.toLabel,'微信零钱');assert.equal(wxTransfers.records[1].recognition.orderStatus,'returned');assert.equal(wxTransfers.records[1].recognition.statusRefundAmount,20000);assert.equal(wxTransfers.records[2].recognition.eventType,'refund');assert.equal(wxTransfers.records[2].recognition.flow.toLabel,'微信零钱');
(async()=>{const buf=fs.readFileSync(path.join(__dirname,'fixtures/statement.xlsx'));const sheets=await c.readXLSX(buf.buffer.slice(buf.byteOffset,buf.byteOffset+buf.byteLength));const x=c.importRows(sheets[0],'微信账单.xlsx');assert.equal(x.records.length,2);assert.equal(x.records[0].amount,2530);assert.equal(x.records[0].merchant,'测试咖啡店');assert.equal(x.records[1].date,'2026-09-18 08:00:00');console.log('PASS: amounts, date validation, quoted CSV, WeChat/Alipay columns, refunds, neutral entries, failed transactions, duplicate IDs, backup validation, compressed XLSX, Excel date cells.');})().catch(e=>{console.error(e);process.exitCode=1;});
