CREATE TABLE schema_version(version INTEGER PRIMARY KEY);
CREATE TABLE transactions(id TEXT PRIMARY KEY,event_type TEXT NOT NULL,status TEXT NOT NULL,occurred_at TEXT NOT NULL,display_amount INTEGER NOT NULL,display_name TEXT NOT NULL,note TEXT NOT NULL,created_at TEXT NOT NULL,deleted_at TEXT);
CREATE TABLE accounts(id TEXT PRIMARY KEY,name TEXT NOT NULL,type TEXT NOT NULL CHECK(type IN ('ASSET','LIABILITY')),balance_tracking TEXT NOT NULL,balance_state TEXT NOT NULL,opening_balance INTEGER NOT NULL,opening_balance_at TEXT NOT NULL,last4 TEXT NOT NULL,deleted_at TEXT);
CREATE TABLE source_records(id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL REFERENCES transactions(id),source_type TEXT NOT NULL,platform TEXT NOT NULL,raw_payload TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE source_identifiers(id TEXT PRIMARY KEY,source_record_id TEXT NOT NULL REFERENCES source_records(id),platform TEXT NOT NULL,identifier_type TEXT NOT NULL,identifier_value TEXT NOT NULL);
CREATE INDEX source_identifier_match ON source_identifiers(platform,identifier_type,identifier_value);
CREATE TABLE balance_movements(id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL REFERENCES transactions(id),account_id TEXT REFERENCES accounts(id),amount INTEGER NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE consumption_effects(id TEXT PRIMARY KEY,transaction_id TEXT NOT NULL REFERENCES transactions(id),amount INTEGER NOT NULL,category_id TEXT,subcategory_id TEXT,effective_at TEXT NOT NULL,created_at TEXT NOT NULL);
CREATE TABLE transaction_links(id TEXT PRIMARY KEY,from_transaction_id TEXT NOT NULL REFERENCES transactions(id),to_transaction_id TEXT NOT NULL REFERENCES transactions(id),type TEXT NOT NULL CHECK(type IN ('REFUND_OF','RETURN_OF')));
CREATE TABLE sync_devices(device_id TEXT PRIMARY KEY);
CREATE TABLE sync_operations(id TEXT PRIMARY KEY,device TEXT NOT NULL,seq INTEGER NOT NULL,payload TEXT NOT NULL,UNIQUE(device,seq));
CREATE TABLE sync_outbox(operation_id TEXT PRIMARY KEY REFERENCES sync_operations(id));
CREATE TABLE sync_applied_ops(operation_id TEXT PRIMARY KEY REFERENCES sync_operations(id));
CREATE TABLE sync_remote_cursors(device TEXT PRIMARY KEY,seq INTEGER NOT NULL);
CREATE TABLE sync_batches(device TEXT NOT NULL,seq INTEGER NOT NULL,checksum TEXT NOT NULL,PRIMARY KEY(device,seq));
CREATE TABLE sync_conflicts(id TEXT PRIMARY KEY,payload TEXT NOT NULL);
CREATE TABLE field_versions(entity_type TEXT NOT NULL,entity_id TEXT NOT NULL,field TEXT NOT NULL,operation_ids TEXT NOT NULL,PRIMARY KEY(entity_type,entity_id,field));
CREATE INDEX movements_by_account ON balance_movements(account_id);
CREATE INDEX effects_by_date ON consumption_effects(effective_at);
INSERT INTO schema_version VALUES(1);
