/* Star Ledger 2 — all monetary values are integer CNY cents. */
const Ledger=(()=>{
const owners=['a','b'],buckets=['liquid','savings'];
const categories=['餐饮美食','购物消费','交通出行','生活日用','休闲娱乐','学习成长','医疗健康','住房缴费','人情往来','工资收入','其他收入','其他'];
const uuid=()=>crypto.randomUUID(),blank=()=>({schema:2,ops:[]}),key=(type,id)=>type+':'+id;
function validateOp(op){if(!op||typeof op.id!=='string'||op.id.length>200||!['tx','account','debt','category','tag','profile','rule','purge'].includes(op.type)||typeof op.entity!=='string'||op.entity.length>1000||['__proto__','prototype','constructor'].includes(op.entity)||!Array.isArray(op.parents)||op.parents.some(p=>typeof p!=='string')||!op.value||typeof op.value!=='object'||typeof op.at!=='string')throw Error('账本版本记录格式错误');validateEntity(op.type,op.value);if(JSON.stringify(op.value).length>150000)throw Error('单条记录过大');return op;}
function merge(...lists){const map=new Map();for(const list of lists){if(!Array.isArray(list)||list.length>250000)throw Error('账本数据格式错误或记录过多');for(const op of list){validateOp(op);const old=map.get(op.id);if(old&&JSON.stringify(old)!==JSON.stringify(op))throw Error('同一版本编号内容不一致，停止合并');map.set(op.id,op);}}const result=[...map.values()];for(const o of result)for(const p of o.parents){const parent=map.get(p);if(!parent||parent.type!==o.type||parent.entity!==o.entity||p===o.id)throw Error('版本依赖缺失或无效，停止合并');}const indegree=new Map(result.map(o=>[o.id,o.parents.length])),children=new Map();for(const o of result)for(const p of o.parents){if(!children.has(p))children.set(p,[]);children.get(p).push(o.id);}const queue=result.filter(o=>!o.parents.length).map(o=>o.id);let visited=0;for(let i=0;i<queue.length;i++){visited++;for(const child of children.get(queue[i])||[]){indegree.set(child,indegree.get(child)-1);if(!indegree.get(child))queue.push(child);}}if(visited!==result.length)throw Error('版本关系循环，无法恢复');return result.sort((a,b)=>a.at.localeCompare(b.at)||a.id.localeCompare(b.id));}
function materialize(ops){const purges=new Map();for(const op of ops){if(op.type==='purge'){const target=op.value.targetType+':'+op.value.targetId;const prev=purges.get(target);if(!prev||op.at>prev.at)purges.set(target,op);}}const groups=new Map();for(const op of ops){if(op.type==='purge')continue;const p=purges.get(key(op.type,op.entity));if(p&&op.at<=p.at)continue;const k=key(op.type,op.entity);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(op);}const entities={tx:{},account:{},debt:{},category:{},tag:{},profile:{},rule:{}};const heads={},conflicts=[];for(const [k,list] of groups){const superseded=new Set(list.flatMap(o=>o.parents)),hs=list.filter(o=>!superseded.has(o.id));heads[k]=hs;if(hs.length!==1){conflicts.push({key:k,heads:hs});continue;}const op=hs[0];entities[op.type][op.entity]={...op.value,id:op.entity,_op:op.id};}return {...entities,heads,conflicts,purges:Object.fromEntries(purges)};}
function compact(ops){const purges=new Map();for(const op of ops)if(op.type==='purge'){const target=op.value.targetType+':'+op.value.targetId;const prev=purges.get(target);if(!prev||op.at>prev.at)purges.set(target,op);}return ops.filter(op=>op.type==='purge'||!purges.has(key(op.type,op.entity))||op.at>purges.get(key(op.type,op.entity)).at);}
function operation(ops,type,id,value,actor,device,parents){const state=parents?null:materialize(ops);return {id:uuid(),type,entity:id,parents:parents||state.heads[key(type,id)]?.map(o=>o.id)||[],value:structuredClone(value),actor,device,at:new Date().toISOString()};}
const active=obj=>Object.values(obj).filter(x=>!x.deleted),amount=v=>Number.isSafeInteger(v)&&v>=0&&v<=99999999900,dateTime=v=>typeof v==='string'&&/^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2}$/.test(v);
function validateEntity(type,v){const text=(x,n=500)=>typeof x==='string'&&x.length<=n,owner=x=>owners.includes(x),bucket=x=>buckets.includes(x);if(type==='purge'){if(!['tx','account','debt','category','tag','profile','rule'].includes(v.targetType)||!text(v.targetId,1000)||!v.targetId.trim())throw Error('删除标记无效');return;}if(v.deleted===true)return;
if(type==='account'&&(!text(v.name,100)||!v.name.trim()||!owner(v.holder)||!/^\d{4}-\d{2}-\d{2}$/.test(v.asOf)||v.balanceAt!=null&&!dateTime(v.balanceAt)||!v.opening||owners.some(o=>buckets.some(b=>!amount(v.opening[o]?.[b])))||v.balanceBasis!=null&&!['historical','current'].includes(v.balanceBasis)))throw Error('请填写账户名称、余额基准时点和四项非负余额');
if(type==='tx'){if(!owner(v.owner)||!['expense','income','transfer','refund','neutral','borrow','repay','lend','collect'].includes(v.kind)||!amount(v.amount)||v.amount===0||!dateTime(v.date)||!bucket(v.bucket)||!text(v.note||'',10000)||!text(v.merchant||'',1000)||!text(v.payerType||'',40)||!Array.isArray(v.tags)||v.tags.length>50||v.tags.some(t=>!text(t,200)))throw Error('账单金额、日期或归属无效');if(v.kind==='transfer'){if(!owner(v.toOwner)||!bucket(v.toBucket)||!['internal','custody','withdraw','deposit','gift','purchase','loan','loan-repay','unassigned'].includes(v.purpose)||v.transferDirection!=null&&!['internal','out','in'].includes(v.transferDirection))throw Error('请确定转账的资金归属与用途');const received=v.receivedAmount==null?v.amount:v.receivedAmount;if(!amount(received)||received===0||received>v.amount)throw Error('到账金额应大于零且不能超过转出金额');}if(v.refund!=null&&(!amount(v.refund)||v.refund>v.amount))throw Error('退款不能超过消费金额');}
if(type==='debt'&&(!owner(v.owner)||!['owed','claim'].includes(v.side)||!amount(v.opening)||!text(v.name,100)||!/^\d{4}-\d{2}-\d{2}$/.test(v.asOf)))throw Error('欠款资料无效');if((type==='category'||type==='tag')&&(!text(v.name,40)||!v.name.trim()||!/^#[\da-f]{6}$/i.test(v.color)))throw Error('名称或颜色无效');if(type==='profile'&&(!text(v.name,30)||!v.name.trim()))throw Error('昵称不能为空');}
const accountBaseAt=a=>a.balanceAt||(a.asOf+' '+(a.balanceBasis==='current'?'23:59:59':'00:00:00'));
function project(state,until='9999-12-31 23:59:59'){
const accounts=active(state.account),txs=active(state.tx),debts=active(state.debt),balances={},issues=[],applied=new Set(),valid=[],owned={a:{liquid:0,savings:0,owed:0,claim:0},b:{liquid:0,savings:0,owed:0,claim:0}},debtBalances={};
for(const a of accounts){balances[a.id]={a:{liquid:0,savings:0},b:{liquid:0,savings:0}};if(accountBaseAt(a)<=until)balances[a.id]=structuredClone(a.opening);}for(const d of debts)debtBalances[d.id]=d.asOf<=until.slice(0,10)?d.opening:0;
const movements=[],linkedRefunds={};for(const r of txs)if(r.kind==='refund'&&r.linkedTo&&!r.pending&&r.date<=until)(linkedRefunds[r.linkedTo]??=[]).push(r);const refundTotals=new Map(Object.entries(linkedRefunds).map(([id,list])=>[id,list.reduce((s,r)=>s+r.amount,0)]));
const add=(t,account,owner,bucket,delta,date=t.date)=>{const a=state.account[account];if(!a||a.deleted){issues.push({id:t.id,reason:'资金账户未指定或已删除'});return false;}const baseAt=accountBaseAt(a),skip=a.balanceBasis==='current'?date<=baseAt:date<baseAt;movements.push({tx:t.id,account,owner,bucket,delta,date,skip});return true;};
for(const t of txs.slice().sort((a,b)=>a.date.localeCompare(b.date)||a.id.localeCompare(b.id))){if(t.date>until)continue;if(t.pending){issues.push({id:t.id,reason:t.pendingReason||'等待确认资金用途或账户'});continue;}if(t.linkedRole==='transfer-leg'){const parent=state.tx[t.linkedTo];if(!parent||parent.deleted||parent.kind!=='transfer')issues.push({id:t.id,reason:'关联转账已删除或存在冲突'});continue;}if(t.kind==='neutral')continue;
if(t.kind==='refund'){const parent=t.linkedTo?state.tx[t.linkedTo]:null;if(parent?.deleted){issues.push({id:t.id,reason:'关联的原交易已删除'});continue;}if(parent&&!['expense','transfer','neutral'].includes(parent.kind)){issues.push({id:t.id,reason:'退款关联的原交易类型无效'});continue;}if(parent?.pending){issues.push({id:t.id,reason:'原交易仍待核对，退款暂不入账'});continue;}if(parent&&(refundTotals.get(parent.id)||0)>parent.amount){issues.push({id:t.id,reason:'关联退款合计超过原交易，请核对'});continue;}const external=['family-card','huabei-repayment-history'].includes(parent?.payerType)||['family-card','huabei-repayment-history'].includes(t.payerType)||((parent?.payerType==='huabei-history'||t.payerType==='huabei-history')&&!t.account);if(!external){if(!state.account[t.account]||state.account[t.account].deleted){issues.push({id:t.id,reason:'退款到账账户未识别'});continue;}add(t,t.account,parent?.owner||t.owner,parent?.bucket||t.bucket,t.amount);}valid.push(t);continue;}
const external=['family-card','huabei-repayment-history'].includes(t.payerType)||(!t.account&&t.payerType==='huabei-history');if(external&&t.kind==='expense'){if((refundTotals.get(t.id)||0)>t.amount)issues.push({id:t.id,reason:'关联退款合计超过原消费，请核对'});valid.push(t);continue;}if(!state.account[t.account]||state.account[t.account].deleted){issues.push({id:t.id,reason:'请选择资金账户'});continue;}if(t.kind==='transfer'){const direction=t.transferDirection||(t.toAccount?'internal':'out');if(direction==='internal'&&(!state.account[t.toAccount]||state.account[t.toAccount].deleted)){issues.push({id:t.id,reason:'请选择转入账户'});continue;}if(direction==='internal'&&t.owner!==t.toOwner&&!['gift','loan','loan-repay'].includes(t.purpose)){issues.push({id:t.id,reason:'代管、存取款和代买不改变资金所有权'});continue;}if(direction==='out'&&!t.toAccount){add(t,t.account,t.owner,t.bucket,-t.amount);valid.push(t);continue;}if(direction==='in'&&!t.toAccount){add(t,t.account,t.owner,t.bucket,t.amount);valid.push(t);continue;}}
if(['borrow','repay','lend','collect'].includes(t.kind)){const d=state.debt[t.debtId];if(!d||d.deleted||d.owner!==t.owner||(d.side==='owed'?!['borrow','repay'].includes(t.kind):!['lend','collect'].includes(t.kind))){issues.push({id:t.id,reason:'请选择匹配的欠款或应收账户'});continue;}if(t.date.slice(0,10)>=d.asOf)debtBalances[d.id]+=['borrow','lend'].includes(t.kind)?t.amount:-t.amount;}
if(t.kind==='expense'){add(t,t.account,t.owner,t.bucket,-t.amount);if((refundTotals.get(t.id)||0)>t.amount)issues.push({id:t.id,reason:'关联退款合计超过原消费，请核对'});if(!(linkedRefunds[t.id]||[]).length&&t.refund>0){if(t.refundDate)add(t,t.refundAccount||t.account,t.owner,t.bucket,t.refund,t.refundDate);else issues.push({id:t.id,reason:'退款时间未确认：消费统计已抵扣，账户退款暂未入账'});}}if(['income','borrow','collect'].includes(t.kind))add(t,t.account,t.owner,t.bucket,t.amount);if(['repay','lend'].includes(t.kind))add(t,t.account,t.owner,t.bucket,-t.amount);
if(t.kind==='transfer'){const received=t.receivedAmount==null?t.amount:t.receivedAmount;add(t,t.account,t.owner,t.bucket,-t.amount);add(t,t.toAccount,t.toOwner,t.toBucket,received,t.transferInDate||t.date);if(['loan','loan-repay'].includes(t.purpose)&&t.owner!==t.toOwner){const lender=t.purpose==='loan'?t.owner:t.toOwner,borrower=lender==='a'?'b':'a',sign=t.purpose==='loan'?1:-1;owned[lender].claim+=sign*t.amount;owned[borrower].owed+=sign*t.amount;}}valid.push(t);}
movements.sort((a,b)=>a.date.localeCompare(b.date));for(const m of movements){if(m.date>until||m.skip)continue;balances[m.account][m.owner][m.bucket]+=m.delta;applied.add(m.tx);}for(const a of accounts)for(const o of owners)for(const b of buckets){owned[o][b]+=balances[a.id][o][b];if(balances[a.id][o][b]<0)issues.push({id:'account:'+a.id,reason:`${a.name} 的${o==='a'?'绿色方':'紫色方'}${b==='liquid'?'流动资金':'存款'}不足，余额待核对`});}for(const d of debts){owned[d.owner][d.side]+=debtBalances[d.id];if(debtBalances[d.id]<0)issues.push({id:'debt:'+d.id,reason:'还款超过欠款，请核对'});}for(const o of owners){if(owned[o].owed<0||owned[o].claim<0)issues.push({id:'pair-debt',reason:'双方还款超过已记录借款，请补全初始债权或核对用途'});owned[o].assets=owned[o].liquid+owned[o].savings+owned[o].claim;owned[o].net=owned[o].assets-owned[o].owed;}return {balances,owned,debtBalances,issues:[...new Map(issues.map(i=>[i.id+'|'+i.reason,i])).values()],valid,movements,applied};}
function netExpense(t,state){const rs=active(state.tx).filter(r=>r.kind==='refund'&&!r.pending&&r.linkedTo===t.id),sum=rs.reduce((s,r)=>s+r.amount,0),refund=rs.length?(sum<=t.amount?sum:0):(t.refund||0);return Math.max(0,t.amount-refund);}
function periodKey(date,group){if(group==='day')return date.slice(0,10);if(group==='month')return date.slice(0,7);const [y,m,d]=date.slice(0,10).split('-').map(Number),dt=new Date(y,m-1,d),day=(dt.getDay()+6)%7;dt.setDate(dt.getDate()-day);return `${dt.getFullYear()}-${String(dt.getMonth()+1).padStart(2,'0')}-${String(dt.getDate()).padStart(2,'0')}`;}
function statisticsRange(state,owner,start,end,group='day'){const p=project(state),validIds=new Set(p.valid.map(t=>t.id)),rows=active(state.tx).filter(t=>(t.owner===owner||t.kind==='transfer'&&t.purpose==='gift'&&t.toOwner===owner)&&t.date>=start&&t.date<=end&&validIds.has(t.id)&&!t.linkedRole);let expense=0,income=0,transferOut=0,transferIn=0;const cats={},series={};const addExpense=(t,n)=>{if(n<=0)return;expense+=n;cats[t.category||'']=(cats[t.category||'']||0)+n;const k=periodKey(t.date,group);series[k]=(series[k]||0)+n;};for(const t of rows){if(t.kind==='expense')addExpense(t,netExpense(t,state));if(t.kind==='transfer'&&t.purpose==='gift'&&t.owner===owner)addExpense(t,t.amount);if(t.kind==='transfer'&&t.owner===owner){const received=t.receivedAmount==null?t.amount:t.receivedAmount,direction=t.transferDirection||(t.toAccount?'internal':'out');if(direction==='out'&&!t.toAccount)transferOut+=t.amount;if(direction==='in'&&!t.toAccount)transferIn+=t.amount;if(direction==='internal')addExpense(t,Math.max(0,t.amount-received));}if(t.kind==='income'||t.kind==='transfer'&&t.purpose==='gift'&&t.toOwner===owner&&t.owner!==owner)income+=t.amount;}return {expense,income,transferOut,transferIn,cats,series,rows};}
function statistics(state,owner,month){const result=statisticsRange(state,owner,month+'-01 00:00:00',month+'-31 23:59:59','day');return {...result,daily:result.series};}
function candidates(state){const rows=active(state.tx).filter(t=>!t.pending&&!t.linkedTo&&['expense','income','neutral','transfer'].includes(t.kind)),result=[];for(const out of rows){const outDirection=out.kind==='transfer'?(out.transferDirection||(out.toAccount?'internal':'out')):'';if(out.kind==='income'||outDirection==='in'||outDirection==='internal')continue;for(const inc of rows){const incDirection=inc.kind==='transfer'?(inc.transferDirection||(inc.toAccount?'internal':'out')):'';if(inc.id===out.id||inc.kind==='expense'||inc.kind==='transfer'&&incDirection!=='in'||inc.account===out.account||!inc.account||!out.account)continue;const expected=out.amount-(out.fee||0);if(inc.amount!==out.amount&&inc.amount!==expected)continue;const diff=Math.abs(Date.parse(out.date.replace(' ','T'))-Date.parse(inc.date.replace(' ','T')));if(diff>172800000)continue;if(!/转账|提现|充值|转入|转出|收款/.test((out.raw?.kind||'')+' '+out.merchant+' '+out.note+' '+(inc.raw?.kind||'')+' '+inc.note))continue;result.push({out,inc,minutes:Math.round(diff/60000),fee:Math.max(0,out.amount-inc.amount)});}}return result.sort((a,b)=>a.minutes-b.minutes).slice(0,40);}
return {owners,buckets,categories,uuid,blank,merge,materialize,compact,operation,active,validateEntity,project,netExpense,statistics,statisticsRange,candidates,accountBaseAt,periodKey};})();
if(typeof module!=='undefined')module.exports=Ledger;
