const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),crypto=require('crypto');
const root=path.resolve('web-dist');
const server=http.createServer((req,res)=>{const url=decodeURIComponent(req.url.split('?')[0]);let f=url.startsWith('/test-fonts/')?path.join(process.cwd(),'node_modules/@fontsource/noto-sans-sc',url.slice(12)):path.join(root,url);if(f.endsWith('/'))f+='index.html';try{res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.woff2':'font/woff2','.webmanifest':'application/manifest+json'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});
const results=[];const ok=s=>{results.push(s);console.log('PASS',s)};
async function db(page){return page.evaluate(()=>new Promise((resolve,reject)=>{const req=indexedDB.open('star-ledger-next-v1');req.onsuccess=()=>{const r=req.result.transaction('ledger').objectStore('ledger').get('main');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);};}));}
async function ready(page){await page.goto('http://127.0.0.1:4173/');await page.locator('.hero-value').waitFor();}
async function nav(page,p){await page.locator(`[data-page=${p}]:visible`).first().click();}
async function newAccount(page,name,amount){await page.locator('[data-action=account]:visible').first().click();const f=page.locator('#account-form');await f.locator('[name=name]').fill(name);await f.locator('[name=balance]').fill(amount);await f.locator('[name=date]').fill('2026-09-01T00:00');await f.locator('[type=submit]').click();await page.locator('dialog').waitFor({state:'hidden'});}
async function newBill(page,kind,name,amount,account,extra={}){await page.locator('[data-action=new]:visible').first().click();await page.locator('#record-kind').selectOption(kind);const f=page.locator('#record-form');await f.locator('[name=name]').fill(name);await f.locator('[name=amount]').fill(amount);await f.locator('[name=date]').fill('2026-09-20T12:00');if(account!==undefined)await f.locator('[name=account]').selectOption(account);for(const[k,v]of Object.entries(extra))await f.locator(`[name=${k}]`).selectOption(v);await f.locator('[type=submit]').click();await page.locator('dialog').waitFor({state:'hidden'});}
async function font(page){if(!fs.existsSync('node_modules/@fontsource/noto-sans-sc/chinese-simplified-400.css'))return;await page.addStyleTag({content:fs.readFileSync('node_modules/@fontsource/noto-sans-sc/chinese-simplified-400.css','utf8').replaceAll('./files/','/test-fonts/files/')+'\n:root{font-family:"Noto Sans SC",sans-serif}'});await page.evaluate(()=>document.fonts.ready);}
(async()=>{await new Promise(r=>server.listen(4173,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],headless:true});try{const context=await browser.newContext({viewport:{width:1440,height:1050},timezoneId:'Asia/Shanghai'});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('requestfailed',r=>console.log('REQUEST_FAILED',r.url(),r.failure()?.errorText));await ready(page);await newAccount(page,'银行卡','1000');await newAccount(page,'微信余额','100');let s=await db(page);const acc=s.ops.filter(o=>o.entity.type==='accounts'&&o.action==='CREATE_ENTITY');const bank=acc[0].entity.id,wallet=acc[1].entity.id;await newBill(page,'PURCHASE','晚餐','44',bank);assert.match(await page.locator('.hero-value').innerText(),/44\.00/);await newBill(page,'INTERNAL_TRANSFER','钱包充值','100',bank,{to:wallet});assert.match(await page.locator('.hero-value').innerText(),/44\.00/);await nav(page,'accounts');const bankCard=page.locator('.account-card[data-account]').filter({hasText:'银行卡'});assert.match(await bankCard.innerText(),/856\.00/);ok('Purchase and internal transfer update separate balance/consumption');await nav(page,'bills');await page.locator('.bill-main').filter({hasText:'晚餐'}).click();await page.locator('[data-refund]').click();const f=page.locator('#record-form');await f.locator('[name=amount]').fill('12');await f.locator('[name=date]').fill('2026-09-21T12:00');await f.locator('[type=submit]').click();await page.locator('dialog').waitFor({state:'hidden'});await nav(page,'home');assert.match(await page.locator('.hero-value').innerText(),/32\.00/);await page.reload();await page.locator('.hero-value').waitFor();assert.match(await page.locator('.hero-value').innerText(),/32\.00/);ok('Partial refund and IndexedDB reload preserve correct totals');
 await nav(page,'bills');await page.locator('.bill-main').filter({hasText:'晚餐'}).first().click();await page.locator('#detail-form [name=note]').fill('<img src=x onerror=alert(1)> #测试');await page.locator('#detail-form [type=submit]').click();await page.locator('dialog').waitFor({state:'hidden'});assert.equal(await page.locator('img[src=x]').count(),0);ok('Notes are persisted and escaped');
 await nav(page,'import');const csv='微信支付账单明细\r\n交易时间,交易类型,交易对方,商品,收/支,金额(元),支付方式,当前状态,交易单号,备注\r\n2026-09-18 12:00:00,商户消费,咖啡店,咖啡,支出,20.00,银行卡,支付成功,wx-unique-001,核验\r\n2026-09-18 13:00:00,退款,咖啡店,退款,收入,5.00,银行卡,退款成功,wx-return-001,退款待关联\r\n';
 async function fileImport(file){await page.evaluate(()=>document.querySelector('#toast').textContent='');const chooser=page.waitForEvent('filechooser');await page.locator('[data-action=import-file]').click();await(await chooser).setFiles(file);await page.waitForFunction(()=>document.querySelector('#toast').textContent.includes('已识别账单')||document.querySelector('#setup-accounts-form'));if(await page.locator('#setup-accounts-form').count()){await page.locator('#setup-accounts-form [type=submit]').click();await page.locator('dialog').waitFor({state:'hidden'});}}
 async function commitNamed(name,account){for(const box of await page.locator('.import-row input[type=checkbox]:enabled').all())await box.uncheck();await page.locator('.import-row').filter({hasText:name}).filter({hasText:'消费'}).locator('input[type=checkbox]').check();await page.locator('[data-action=commit-import]').click();await page.locator('.import-row').filter({hasText:name}).filter({hasText:'消费'}).waitFor({state:'hidden'});}
 await fileImport({name:'wechat.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});assert.equal(await page.locator('.import-row').count(),2);await commitNamed('咖啡店',bank);const before=(await db(page)).ops.length;await fileImport({name:'wechat.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});assert.equal((await db(page)).ops.length,before);ok('CSV review and repeat import avoid duplicate accounting');
 await fileImport('tests/fixtures/wechat.xlsx');await commitNamed('XLSX 食堂',wallet);ok('Actual read-excel-file XLSX parsing and import');
 await nav(page,'bills');await page.locator('.bill-main').filter({hasText:'XLSX 食堂'}).click();await page.locator('[data-delete]').click();await page.locator('#confirm-form [type=submit]').click();await page.locator('dialog').waitFor({state:'hidden'});await page.locator('[data-action=trash]').click();await page.locator('[data-restore]').click();await page.locator('dialog').getByText('回收站是空的。').waitFor();await page.locator('[data-close]').click();ok('Tombstone delete and restore update visible bills');
 // Real crypto, GitHub HTTP mock: two independent browser databases exchange encrypted commands.
 const remote=new Map();const route=async route=>{const req=route.request(),u=new URL(req.url()),prefix='/repos/test-owner/private-ledger';const p=u.pathname.slice(prefix.length);const json=(v,status=200)=>route.fulfill({status,headers:{'access-control-allow-origin':'*','access-control-allow-headers':'*','access-control-allow-methods':'GET,PUT,OPTIONS'},contentType:'application/json',body:JSON.stringify(v)});if(!u.pathname.startsWith(prefix)){console.log('ROUTE_MISMATCH',u.pathname);return route.abort();}if(req.method()==='OPTIONS')return json({});if(!p)return json({private:true});if(p.startsWith('/git/trees/'))return json({truncated:false,tree:[...remote.entries()].map(([path,v])=>({path,sha:v.sha,type:'blob',mode:'100644',size:Buffer.byteLength(v.text)}))});if(p.startsWith('/git/blobs/')){const v=[...remote.values()].find(x=>x.sha===p.split('/').pop());return json({encoding:'base64',content:Buffer.from(v.text).toString('base64')});}if(p.startsWith('/contents/')){const key=decodeURIComponent(p.slice(10));if(req.method()==='PUT'){const body=req.postDataJSON();const text=Buffer.from(body.content,'base64').toString();assert.ok(!text.includes('晚餐'));remote.set(key,{text,sha:crypto.createHash('sha1').update(text).digest('hex')});return json({},201);}const v=remote.get(key);return v?json({encoding:'base64',content:Buffer.from(v.text).toString('base64')}):json({},404);}return json({},404);};await context.route('https://api.github.com/**',route);const key=crypto.randomBytes(32).toString('base64url');async function sync(page){await page.locator('[data-action=sync]:visible').first().click();for(const[n,v]of Object.entries({owner:'test-owner',repo:'private-ledger',branch:'main',ledger:'web-e2e',token:'test-token',key}))await page.locator(`#sync-form [name=${n}]`).fill(v);await page.locator('#sync-form [type=submit]').click();try{await page.locator('dialog').waitFor({state:'hidden',timeout:10000});}catch(e){console.log('SYNC_FAILURE',await page.locator('#toast').innerText(),await page.locator('#sync-progress').innerText());throw e;}}
 await sync(page);const context2=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Shanghai'});await context2.route('https://api.github.com/**',route);const phone=await context2.newPage();phone.on('pageerror',e=>errors.push(e.message));await ready(phone);await nav(phone,'settings');await sync(phone);assert.equal((await db(phone)).ops.length,(await db(page)).ops.length);await nav(phone,'bills');await phone.locator('.bill-main').filter({hasText:'咖啡店'}).click();await phone.locator('#detail-form [name=note]').fill('手机修改成功');await phone.locator('#detail-form [type=submit]').click();await phone.locator('dialog').waitFor({state:'hidden'});await nav(phone,'settings');await sync(phone);await sync(page);assert.ok((await db(page)).ops.some(o=>o.entity.fields.note==='手机修改成功'));assert.ok(!JSON.stringify(await db(page)).includes('test-token'));ok('Two browser devices encrypt, sync, restore and reverse-sync notes without persisting credentials');
 const saved=await db(page);const backupText=JSON.stringify({format:'star-ledger-web-backup',version:1,operations:saved.ops,settings:saved.settings});const context3=await browser.newContext({viewport:{width:1280,height:900},timezoneId:'Asia/Shanghai'});await context3.route('https://api.github.com/**',route);const restored=await context3.newPage();await ready(restored);await nav(restored,'settings');let restoreChooser=restored.waitForEvent('filechooser');await restored.locator('[data-action=restore]').click();await(await restoreChooser).setFiles({name:'backup.json',mimeType:'application/json',buffer:Buffer.from(backupText)});await restored.locator('#confirm-form [type=submit]').click();await restored.locator('dialog').waitFor({state:'hidden'});const remoteCount=remote.size;await sync(restored);assert.equal(remote.size,remoteCount);assert.equal((await db(restored)).pending.length,0);ok('Backup recovery recognizes existing encrypted remote commands without duplicate uploads');

 await nav(phone,'home');await phone.evaluate(()=>navigator.serviceWorker.ready);await phone.reload();await phone.locator('.hero-value').waitFor();await context2.setOffline(true);await phone.reload();await phone.locator('.hero-value').waitFor();await newBill(phone,'PURCHASE','离线早餐','8',wallet);await context2.setOffline(false);ok('Cached application reloads and writes real transactions offline');
 for(const name of ['home','bills','accounts','analysis','import','settings']){await nav(phone,name).catch(async()=>{await phone.goto('http://127.0.0.1:4173/#'+name);});await phone.waitForTimeout(120);assert.equal(await phone.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true,'mobile overflow on '+name);}ok('All six mobile pages fit 390px viewport');
 // Visual review: separate sample ledger, never seed a real user account automatically.
 const visual=await browser.newContext({viewport:{width:1440,height:1050},timezoneId:'Asia/Shanghai'});const vp=await visual.newPage();await ready(vp);await vp.locator('[data-action=demo]').first().click();await vp.getByText('你正在查看演示账本',{exact:false}).waitFor();await font(vp);await vp.evaluate(()=>document.querySelector('#toast').classList.remove('show'));await vp.screenshot({path:'desktop-reviewed.png',fullPage:true});await vp.setViewportSize({width:390,height:844});await vp.waitForTimeout(300);await vp.screenshot({path:'mobile-reviewed.png',fullPage:true});assert.equal(errors.length,0,errors.join('\n'));ok('No browser runtime errors in exercised workflows');fs.writeFileSync('docs/web-validation.json',JSON.stringify({date:new Date().toISOString(),browser:browser.version(),results,limitations:['GitHub sync transport mocked; actual browser-to-GitHub authorization requires user credentials','Android/iOS real devices not tested','OCR and live CDN availability not exercised in this run']},null,2));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
