import test from 'node:test';
import assert from 'node:assert/strict';
import {BusinessAccountingService} from '../packages/accounting/business.ts';
import {accountBalance,consumptionInPeriod,unresolvedMovements} from '../packages/analytics/index.ts';
import {project} from '../packages/sync/projection.ts';
import {pair,converge,patch} from './helpers.ts';
import type {BusinessCommand} from '../packages/domain/accounting.ts';
const opening='2026-08-01T00:00:00Z',date='2026-09-20T10:00:00Z',later='2026-09-21T10:00:00Z',end='2026-10-31T23:59:59Z';
function setup(t:Parameters<typeof pair>[0]) {
 const p=pair(t),service=new BusinessAccountingService(p.a.store,'a');
 for(const [id,type,balance] of [['bank','ASSET',1000000],['wallet','ASSET',200000],['credit','LIABILITY',0]] as const)
  service.execute({kind:'CREATE_ACCOUNT',id,name:id,accountType:type,openingBalance:balance,openingBalanceAt:opening});
 const snapshot=()=>project(p.a.store.allOperations());
 return {...p,service,snapshot,balance:(id:string)=>accountBalance(snapshot(),id,end).balance,
  spent:(start='2026-09-01T00:00:00Z',finish='2026-10-01T00:00:00Z')=>consumptionInPeriod(snapshot(),start,finish)};
}
const base=(id:string,occurredAt=date)=>({id,occurredAt,name:'Merchant A'});
test('bank card purchase: bank -44, consumption +44',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:4400,payer:'bank',categoryId:'food'});assert.equal(x.balance('bank'),995600);assert.equal(x.spent(),4400);});
test('wallet purchase uses its own account',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:4400,payer:'wallet'});assert.equal(x.balance('wallet'),195600);assert.equal(x.balance('bank'),1000000);});
test('family card purchase counts consumption without owned balance movement',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:4400,payer:null,funding:'EXTERNAL_SPONSOR'});assert.equal(x.balance('bank'),1000000);assert.equal(x.spent(),4400);assert.equal(unresolvedMovements(x.snapshot()).length,0);});
test('full refund reverses consumption and restores funds',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:4400,payer:'bank'});x.service.execute({...base('refund',later),kind:'REFUND',amount:4400,originalId:'buy',destination:'bank'});assert.equal(x.balance('bank'),1000000);assert.equal(x.spent(),0);assert.equal(x.a.store.get('transaction_links','refund:link')?.fields.type,'REFUND_OF');});
test('partial refund reduces both by the actual refunded amount',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:10000,payer:'bank'});x.service.execute({...base('refund',later),kind:'REFUND',amount:3000,originalId:'buy',destination:'bank'});assert.equal(x.balance('bank'),993000);assert.equal(x.spent(),7000);});
test('cross-month refund affects the refund month and leaves original month intact',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:10000,payer:'bank'});x.service.execute({...base('refund','2026-10-02T10:00:00Z'),kind:'REFUND',amount:3000,originalId:'buy',destination:'bank'});assert.equal(x.spent(),10000);assert.equal(x.spent('2026-10-01T00:00:00Z','2026-11-01T00:00:00Z'),-3000);});
test('external transfer is not consumption by default',t=>{const x=setup(t);x.service.execute({...base('transfer'),kind:'EXTERNAL_TRANSFER',amount:10000,from:'bank'});assert.equal(x.balance('bank'),990000);assert.equal(x.spent(),0);});
test('external transfer return restores money without creating income/consumption',t=>{const x=setup(t);x.service.execute({...base('transfer'),kind:'EXTERNAL_TRANSFER',amount:10000,from:'bank'});x.service.execute({...base('return',later),kind:'RETURN',amount:10000,originalId:'transfer',destination:'bank'});assert.equal(x.balance('bank'),1000000);assert.equal(x.spent(),0);});
test('bank top-up to wallet preserves total assets and consumption',t=>{const x=setup(t);x.service.execute({...base('topup'),kind:'INTERNAL_TRANSFER',amount:10000,from:'bank',to:'wallet'});assert.equal(x.balance('bank'),990000);assert.equal(x.balance('wallet'),210000);assert.equal(x.spent(),0);});
test('withdraw 1500 with fee 1.50: consumption is 1.50, not 1501.50',t=>{const x=setup(t);x.service.execute({...base('withdraw'),kind:'WITHDRAWAL',amount:150000,fee:150,from:'wallet',to:'bank'});assert.equal(x.balance('wallet'),49850);assert.equal(x.balance('bank'),1150000);assert.equal(x.spent(),150);});
test('red packet can be explicitly marked as consumption',t=>{const x=setup(t);x.service.execute({...base('gift'),kind:'RED_PACKET',amount:20000,from:'wallet',consumptionAmount:20000,categoryId:'gifts'});assert.equal(x.balance('wallet'),180000);assert.equal(x.spent(),20000);});
test('credit purchase increases debt; repayment reduces debt without recounting consumption',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:4400,payer:'credit'});assert.equal(x.balance('credit'),4400);x.service.execute({...base('repay',later),kind:'REPAYMENT',amount:4400,from:'bank',to:'credit'});assert.equal(x.balance('credit'),0);assert.equal(x.balance('bank'),995600);assert.equal(x.spent(),4400);});
test('refund to credit account reduces debt',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:4400,payer:'credit'});x.service.execute({...base('refund',later),kind:'REFUND',amount:1400,originalId:'buy',destination:'credit'});assert.equal(x.balance('credit'),3000);assert.equal(x.spent(),3000);});
test('deposit with partial return does not infer consumption for the remainder',t=>{const x=setup(t);x.service.execute({...base('deposit'),kind:'DEPOSIT',amount:10000,from:'bank'});x.service.execute({...base('return',later),kind:'RETURN',amount:8000,originalId:'deposit',destination:'bank'});assert.equal(x.balance('bank'),998000);assert.equal(x.spent(),0);});
test('adding consumption meaning changes statistics but preserves balance and source',t=>{const x=setup(t);x.service.execute({...base('transfer'),kind:'EXTERNAL_TRANSFER',amount:10000,from:'bank',source:{id:'s',sourceType:'EXCEL',platform:'WECHAT',rawPayload:'{"amount":"100.00","status":"成功"}'}});const before=x.a.store.get('source_records','s');x.service.execute({kind:'SET_CONSUMPTION',transactionId:'transfer',amount:7000,categoryId:'food'});assert.equal(x.spent(),7000);assert.equal(x.balance('bank'),990000);assert.deepEqual(x.a.store.get('source_records','s'),before);});
test('unknown payer is an unresolved movement, not a sponsored payment',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:4400,payer:null});assert.equal(x.spent(),4400);assert.equal(unresolvedMovements(x.snapshot())[0].fields.amount,-4400);assert.equal(x.balance('bank'),1000000);});
test('unknown internal destination preserves both movement legs',t=>{const x=setup(t);x.service.execute({...base('topup'),kind:'INTERNAL_TRANSFER',amount:10000,from:'bank',to:null});assert.equal(x.balance('bank'),990000);assert.equal(unresolvedMovements(x.snapshot())[0].fields.amount,10000);assert.equal(x.spent(),0);});
test('pending and failed purchases have evidence but no accounting effects',t=>{const x=setup(t);for(const status of ['PENDING','FAILED'] as const)x.service.execute({...base(status),kind:'PURCHASE',amount:4400,payer:'bank',status});assert.equal(x.spent(),0);assert.equal(x.balance('bank'),1000000);assert.ok(x.a.store.get('transactions','PENDING'));});
test('cumulative over-refund is rejected without partial writes',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:10000,payer:'bank'});x.service.execute({...base('r1',later),kind:'REFUND',amount:6000,originalId:'buy',destination:'bank'});const count=x.a.store.allOperations().length;assert.throws(()=>x.service.execute({...base('r2',later),kind:'REFUND',amount:5000,originalId:'buy',destination:'bank'}),/RETURN_EXCEEDS_ORIGINAL/);assert.equal(x.a.store.allOperations().length,count);assert.equal(x.a.store.get('transactions','r2'),undefined);});
test('mixed transfer return requires explicit consumption allocation',t=>{const x=setup(t);x.service.execute({...base('transfer'),kind:'EXTERNAL_TRANSFER',amount:10000,from:'bank',consumptionAmount:3000});assert.throws(()=>x.service.execute({...base('r',later),kind:'RETURN',amount:2000,originalId:'transfer',destination:'bank'}),/CONSUMPTION_ALLOCATION_REQUIRED/);x.service.execute({...base('r',later),kind:'RETURN',amount:2000,originalId:'transfer',destination:'bank',consumptionReduction:1000});assert.equal(x.spent(),2000);});
test('family-card refund changes consumption without touching owned assets',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:4400,payer:null,funding:'EXTERNAL_SPONSOR'});x.service.execute({...base('refund',later),kind:'REFUND',amount:4400,originalId:'buy',destination:null});assert.equal(x.spent(),0);assert.equal(unresolvedMovements(x.snapshot()).length,0);assert.equal(x.balance('bank'),1000000);});
test('opening balance excludes older imported movements but consumption remains',t=>{const x=setup(t);x.service.execute({kind:'CREATE_ACCOUNT',id:'new',name:'new',accountType:'ASSET',openingBalance:10000,openingBalanceAt:'2026-09-25T00:00:00Z'});x.service.execute({...base('old'),kind:'PURCHASE',amount:3000,payer:'new'});assert.equal(x.balance('new'),10000);assert.equal(x.spent(),3000);assert.equal(accountBalance(x.snapshot(),'new',end).excludedHistoricalMovements,1);});
test('uninitialized balance stays unknown rather than pretending to be zero',t=>{const x=setup(t);x.service.execute({kind:'CREATE_ACCOUNT',id:'unknown',name:'unknown',accountType:'ASSET',openingBalance:null,openingBalanceAt:opening});x.service.execute({...base('buy'),kind:'PURCHASE',amount:1000,payer:'unknown'});assert.equal(x.balance('unknown'),null);assert.equal(x.spent(),1000);});
test('tombstone removes effects from derived totals while retaining evidence',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:4400,payer:'bank'});x.a.service.execute([{action:'DELETE_ENTITY',entity:{type:'transactions',id:'buy',fields:{deleted_at:later}}}]);assert.equal(x.spent(),0);assert.equal(x.balance('bank'),1000000);assert.ok(x.a.store.get('balance_movements','buy:movement:0'));});
test('financial command synchronizes all facts and gives equal derived results',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:4400,payer:'bank'});converge(x.a,x.b);const s=project(x.b.store.allOperations());assert.equal(accountBalance(s,'bank',end).balance,x.balance('bank'));assert.equal(consumptionInPeriod(s,'2026-09-01T00:00:00Z','2026-10-01T00:00:00Z'),4400);});
test('derived totals refuse unresolved conflicts instead of using provisional values',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:4400,payer:'bank'});converge(x.a,x.b);x.a.service.execute([patch('consumption_effects','buy:effect','category_id','food')]);x.b.service.execute([patch('consumption_effects','buy:effect','category_id','travel')]);converge(x.a,x.b);assert.throws(()=>x.spent(),/UNRESOLVED_CONFLICT/);});
test('invalid money, calendar date, same-account transfer and wrong repayment are rejected',t=>{const x=setup(t);const invalid:BusinessCommand[]=[{...base('a'),kind:'PURCHASE',amount:44.01,payer:'bank'},{...base('b','2026-02-30T10:00:00Z'),kind:'PURCHASE',amount:100,payer:'bank'},{...base('c'),kind:'INTERNAL_TRANSFER',amount:100,from:'bank',to:'bank'},{...base('d'),kind:'REPAYMENT',amount:100,from:'bank',to:'wallet'}];for(const c of invalid)assert.throws(()=>x.service.execute(c));assert.equal(x.spent(),0);});

test('individually legal concurrent refunds become an explicit aggregate conflict',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:10000,payer:'bank'});converge(x.a,x.b);const other=new BusinessAccountingService(x.b.store,'b');x.service.execute({...base('r1',later),kind:'REFUND',amount:6000,originalId:'buy',destination:'bank'});other.execute({...base('r2',later),kind:'REFUND',amount:6000,originalId:'buy',destination:'bank'});converge(x.a,x.b);assert.equal(x.a.store.conflicts()[0].field,'$accounting');assert.deepEqual(x.a.store.conflicts(),x.b.store.conflicts());assert.throws(()=>x.spent(),/UNRESOLVED_CONFLICT/);x.service.execute({kind:'DELETE_TRANSACTION',transactionId:'r2',deletedAt:later});converge(x.a,x.b);assert.deepEqual(x.a.store.conflicts(),[]);assert.equal(x.spent(),4000);});
test('delete original versus newly created refund is detected across devices',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:10000,payer:'bank'});converge(x.a,x.b);const other=new BusinessAccountingService(x.b.store,'b');x.service.execute({kind:'DELETE_TRANSACTION',transactionId:'buy',deletedAt:later});other.execute({...base('r',later),kind:'REFUND',amount:1000,originalId:'buy',destination:'bank'});converge(x.a,x.b);assert.equal(x.a.store.conflicts()[0].field,'$accounting');assert.throws(()=>x.spent(),/UNRESOLVED_CONFLICT/);});
test('deleting a purchase with active refunds is rejected by business service',t=>{const x=setup(t);x.service.execute({...base('buy'),kind:'PURCHASE',amount:10000,payer:'bank'});x.service.execute({...base('r',later),kind:'REFUND',amount:1000,originalId:'buy',destination:'bank'});assert.throws(()=>x.service.execute({kind:'DELETE_TRANSACTION',transactionId:'buy',deletedAt:later}),/ACTIVE_RETURN_LINKS/);});
test('income increases funds without negative consumption',t=>{const x=setup(t);x.service.execute({...base('income'),kind:'INCOME',amount:50000,destination:'bank'});assert.equal(x.balance('bank'),1050000);assert.equal(x.spent(),0);});
