import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {SqliteStore} from '../packages/storage/index.ts';
import {FakeSyncProvider} from '../packages/sync/index.ts';
import {device,pair,seed,converge,create,transaction,effect,patch} from './helpers.ts';
test('schema migration persists data and device identity across reopen',()=>{
 const dir=mkdtempSync(join(tmpdir(),'ledger-'));try {
  const path=join(dir,'a.db'),r=new FakeSyncProvider();let a=device('a',r,path);a.service.execute([create(transaction())]);a.store.close();
  a=device('a',r,path);assert.equal(a.store.get('transactions','t')?.fields.display_amount,4400);assert.equal(a.store.allOperations().length,1);a.store.close();
  assert.throws(()=>new SqliteStore(path,'b'),/DEVICE_ID_MISMATCH/);
 }finally{rmSync(dir,{recursive:true,force:true});}
});
test('failure between business write and outbox rolls back everything',t=>{const {a}=pair(t);assert.throws(()=>a.service.execute([create(transaction())],()=>{throw Error('crash');}));assert.equal(a.store.get('transactions','t'),undefined);assert.equal(a.store.allOperations().length,0);assert.equal(a.store.db.prepare('SELECT count(*) n FROM field_versions').get()?.n,0);a.service.execute([create(transaction())]);assert.equal(a.store.allOperations()[0].seq,1);});
test('actual outbox INSERT failure rolls back business and operation',t=>{const {a}=pair(t);a.store.db.exec("CREATE TRIGGER fail_outbox BEFORE INSERT ON sync_outbox BEGIN SELECT RAISE(ABORT,'disk fault'); END;");assert.throws(()=>a.service.execute([create(transaction())]),/disk fault/);assert.equal(a.store.get('transactions','t'),undefined);assert.equal(a.store.allOperations().length,0);});
test('independent offline creations converge',t=>{const {a,b}=pair(t);a.service.execute([create(transaction('one'))]);b.service.execute([create(transaction('two'))]);converge(a,b);for(const id of ['one','two'])assert.deepEqual(a.store.get('transactions',id),b.store.get('transactions',id));});
test('replaying ten times is idempotent and does not echo remote ops',t=>{const {a,b}=pair(t);seed(a,b);for(let i=0;i<10;i++)b.sync.download();assert.equal(b.store.allOperations().length,2);assert.equal(b.store.db.prepare('SELECT count(*) n FROM sync_outbox').get()?.n,0);});
test('category and note edits merge independently',t=>{const {a,b}=pair(t);seed(a,b);a.service.execute([patch('consumption_effects','e','category_id','food')]);b.service.execute([patch('transactions','t','note','dinner')]);converge(a,b);for(const d of [a,b]){assert.equal(d.store.get('consumption_effects','e')?.fields.category_id,'food');assert.equal(d.store.get('transactions','t')?.fields.note,'dinner');assert.deepEqual(d.store.conflicts(),[]);}});
test('different concurrent categories produce one stable conflict',t=>{const {a,b}=pair(t);seed(a,b);a.service.execute([patch('consumption_effects','e','category_id','food')]);b.service.execute([patch('consumption_effects','e','category_id','fun')]);converge(a,b);assert.equal(a.store.conflicts().length,1);assert.deepEqual(a.store.conflicts(),b.store.conflicts());assert.equal(a.store.conflicts()[0].candidates.length,2);});
test('equal concurrent category edits merge without conflict',t=>{const {a,b}=pair(t);seed(a,b);for(const d of [a,b])d.service.execute([patch('consumption_effects','e','category_id','food')]);converge(a,b);assert.deepEqual(a.store.conflicts(),[]);assert.deepEqual(b.store.conflicts(),[]);});
test('causally later category edit supersedes both equal heads',t=>{const {a,b}=pair(t);seed(a,b);for(const d of [a,b])d.service.execute([patch('consumption_effects','e','category_id','food')]);converge(a,b);a.service.execute([patch('consumption_effects','e','category_id','fun')]);converge(a,b);assert.equal(b.store.get('consumption_effects','e')?.fields.category_id,'fun');assert.deepEqual(b.store.conflicts(),[]);});
test('delete versus note edit keeps both and requires explicit resolution',t=>{const {a,b}=pair(t);seed(a,b);a.service.execute([{action:'DELETE_ENTITY',entity:{type:'transactions',id:'t',fields:{deleted_at:'2026-09-28T10:00:00Z'}}}]);b.service.execute([patch('transactions','t','note','keep')]);converge(a,b);assert.equal(a.store.conflicts()[0].field,'$lifecycle');assert.deepEqual(a.store.conflicts(),b.store.conflicts());assert.equal(a.store.get('transactions','t')?.fields.deleted_at,null);a.service.execute([{action:'RESOLVE_CONFLICT',entity:{type:'transactions',id:'t',fields:{deleted_at:null}}}]);converge(a,b);assert.deepEqual(b.store.conflicts(),[]);assert.equal(b.store.get('transactions','t')?.fields.note,'keep');});
test('conflict resolution propagates and is replay-safe',t=>{const {a,b}=pair(t);seed(a,b);a.service.execute([patch('consumption_effects','e','category_id','food')]);b.service.execute([patch('consumption_effects','e','category_id','fun')]);converge(a,b);a.service.execute([{action:'RESOLVE_CONFLICT',entity:{type:'consumption_effects',id:'e',fields:{category_id:'travel'}}}]);converge(a,b);b.sync.download();assert.deepEqual(b.store.conflicts(),[]);assert.equal(b.store.get('consumption_effects','e')?.fields.category_id,'travel');});
test('upload acknowledged remotely then crash retries same complete command',t=>{const {a,b,remote}=pair(t);a.service.execute([create(transaction()),create(effect())]);assert.throws(()=>a.sync.upload(()=>{throw Error('crash');}));a.sync.upload();assert.equal(remote.batches.size,1);assert.equal([...remote.batches.values()][0].operations.length,2);b.sync.download();assert.equal(b.store.allOperations().length,2);});
test('download failure rolls back data operations and cursor',t=>{const {a,b}=pair(t);a.service.execute([create(transaction())]);a.sync.upload();assert.throws(()=>b.sync.download(()=>{throw Error('crash');}));assert.equal(b.store.allOperations().length,0);assert.equal(b.store.get('transactions','t'),undefined);assert.equal(b.store.db.prepare('SELECT count(*) n FROM sync_remote_cursors').get()?.n,0);b.sync.download();assert.ok(b.store.get('transactions','t'));});
test('seven simulated offline days retain edits then synchronize',t=>{const {a,b,remote}=pair(t);remote.online=false;for(let day=1;day<=7;day++){a.service.execute([create(transaction(`a${day}`))]);b.service.execute([create(transaction(`b${day}`))]);assert.throws(()=>a.sync.sync(),/OFFLINE/);}remote.online=true;converge(a,b);assert.equal(a.store.allOperations().length,14);assert.equal(b.store.allOperations().length,14);});
test('corrupt batch rejects the entire pull without touching local facts',t=>{const {a,b,remote}=pair(t);a.service.execute([create(transaction())]);a.sync.upload();[...remote.batches.values()][0].operations[0].entity.fields.display_amount=999;assert.throws(()=>b.sync.download(),/CORRUPT_BATCH/);assert.equal(b.store.allOperations().length,0);});
test('missing sequence blocks pull and retry succeeds when restored',t=>{const {a,b,remote}=pair(t);a.service.execute([create(transaction('first'))]);a.service.execute([create(transaction('second'))]);a.sync.upload();const first=remote.batches.get('a:1')!;remote.batches.delete('a:1');assert.throws(()=>b.sync.download(),/SEQUENCE_GAP/);assert.equal(b.store.allOperations().length,0);remote.upload(first);b.sync.download();assert.equal(b.store.allOperations().length,2);});
test('new device restores the full simulated ledger',t=>{const {a,b,remote}=pair(t);seed(a,b);b.service.execute([patch('transactions','t','note','restored')]);b.sync.upload();const c=device('c',remote);try{c.sync.download();assert.equal(c.store.get('transactions','t')?.fields.note,'restored');assert.ok(c.store.get('consumption_effects','e'));}finally{c.store.close();}});
test('invalid money and unknown field are rejected',t=>{const {a}=pair(t);const e=transaction();e.fields.display_amount=44.01;assert.throws(()=>a.service.execute([create(e)]),/INVALID_VALUE/);a.service.execute([create(transaction())]);assert.throws(()=>a.service.execute([patch('transactions','t','typo','x')]),/INVALID_FIELD/);});
test('foreign key failure rolls back the complete command',t=>{const {a}=pair(t);assert.throws(()=>a.service.execute([create(transaction()),create(effect('e','missing'))]),/FOREIGN KEY/);assert.equal(a.store.allOperations().length,0);assert.equal(a.store.get('transactions','t'),undefined);});
test('source evidence is immutable',t=>{const {a}=pair(t);a.service.execute([create(transaction()),create({type:'source_records',id:'s',fields:{transaction_id:'t',source_type:'MANUAL',platform:'TEST',raw_payload:'{"amount":"44.00"}',created_at:'2026-09-28T09:00:00Z'}})]);assert.throws(()=>a.service.execute([patch('source_records','s','raw_payload','changed')]),/IMMUTABLE_SOURCE/);});
test('same operation id with different payload is rejected even with valid checksum',t=>{const {a,b,remote}=pair(t);seed(a,b);const batch=[...remote.batches.values()][0];batch.operations[0].entity.fields.note='tamper';const {checksum,...body}=batch;batch.checksum=createHash('sha256').update(JSON.stringify(body)).digest('hex');assert.throws(()=>b.sync.download(),/OPERATION_COLLISION/);});

test('transaction deletion conflicts with concurrent child category change',t=>{const {a,b}=pair(t);seed(a,b);a.service.execute([{action:'DELETE_ENTITY',entity:{type:'transactions',id:'t',fields:{deleted_at:'2026-09-28T10:00:00Z'}}}]);b.service.execute([patch('consumption_effects','e','category_id','food')]);converge(a,b);assert.equal(a.store.conflicts()[0].field,'$lifecycle');assert.deepEqual(a.store.conflicts(),b.store.conflicts());assert.equal(b.store.get('transactions','t')?.fields.deleted_at,null);});
test('ordinary patch cannot silently resolve a known conflict',t=>{const {a,b}=pair(t);seed(a,b);a.service.execute([patch('consumption_effects','e','category_id','food')]);b.service.execute([patch('consumption_effects','e','category_id','fun')]);converge(a,b);assert.throws(()=>a.service.execute([patch('consumption_effects','e','category_id','travel')]),/EXPLICIT_RESOLUTION_REQUIRED/);});
test('edits under a known deleted parent are blocked',t=>{const {a,b}=pair(t);seed(a,b);a.service.execute([{action:'DELETE_ENTITY',entity:{type:'transactions',id:'t',fields:{deleted_at:'2026-09-28T10:00:00Z'}}}]);assert.throws(()=>a.service.execute([patch('consumption_effects','e','category_id','food')]),/PARENT_DELETED/);});
test('incomplete aggregate batch with recalculated checksum is still rejected',t=>{const {a,b,remote}=pair(t);a.service.execute([create(transaction()),create(effect())]);a.sync.upload();const batch=[...remote.batches.values()][0];batch.operations.pop();const {checksum,...body}=batch;batch.checksum=createHash('sha256').update(JSON.stringify(body)).digest('hex');assert.throws(()=>b.sync.download(),/INVALID_BATCH_HEADER/);assert.equal(b.store.allOperations().length,0);});
