import test from 'node:test';
import assert from 'node:assert/strict';
import {BusinessAccountingService} from '../packages/accounting/business.ts';
import {accountBalance,consumptionInPeriod} from '../packages/analytics/index.ts';
import {project} from '../packages/sync/projection.ts';
import {pair,converge,patch} from './helpers.ts';
const date='2026-09-20T10:00:00Z',start='2026-09-01T00:00:00Z',end='2026-10-01T00:00:00Z';
const buy={kind:'PURCHASE' as const,id:'buy',name:'Lunch',amount:4400,payer:'bank',occurredAt:date,note:'keep #tag',source:{id:'original',sourceType:'SCREENSHOT' as const,platform:'TEST',rawPayload:'original 44'}};
const correction={kind:'CORRECT_AMOUNT' as const,transactionId:'buy',amount:4000,expectedAmount:4400,reason:'Input error',correctedAt:date,sourceId:'audit-a'};
function setup(t:Parameters<typeof pair>[0]){const p=pair(t),sa=new BusinessAccountingService(p.a.store,'a'),sb=new BusinessAccountingService(p.b.store,'b');for(const [id,type] of [['bank','ASSET'],['credit','LIABILITY']] as const)sa.execute({kind:'CREATE_ACCOUNT',id,name:id,accountType:type,openingBalance:type==='ASSET'?100000:0,openingBalanceAt:start});const snapshot=()=>project(p.a.store.allOperations());return {...p,sa,sb,snapshot,balance:(id='bank')=>accountBalance(snapshot(),id,end).balance,spent:()=>consumptionInPeriod(snapshot(),start,end)};}
test('amount correction preserves identity and evidence, changes totals once and syncs',t=>{const x=setup(t);x.sa.execute(buy);const source=x.a.store.get('source_records','original');x.sa.execute(correction);assert.equal(x.balance(),96000);assert.equal(x.spent(),4000);assert.equal(x.a.store.get('transactions','buy')?.fields.note,'keep #tag');assert.deepEqual(x.a.store.get('source_records','original'),source);assert.match(String(x.a.store.get('source_records','audit-a')?.fields.raw_payload),/Input error/);converge(x.a,x.b);assert.deepEqual(x.snapshot().entities,project(x.b.store.allOperations()).entities);});
test('credit and sponsor corrections preserve distinct balance rules',t=>{const x=setup(t);x.sa.execute({...buy,payer:'credit'});x.sa.execute(correction);assert.equal(x.balance('credit'),4000);x.sa.execute({...buy,id:'family',source:undefined,payer:null,funding:'EXTERNAL_SPONSOR'});x.sa.execute({...correction,transactionId:'family',sourceId:'family-audit'});assert.equal(x.spent(),8000);assert.equal(x.balance(),100000);assert.equal(x.balance('credit'),4000);});
test('income correction changes balance without consumption',t=>{const x=setup(t);x.sa.execute({kind:'INCOME',id:'buy',name:'income',amount:4400,destination:'bank',occurredAt:date});x.sa.execute(correction);assert.equal(x.balance(),104000);assert.equal(x.spent(),0);});
test('stale, invalid, linked and unsupported corrections leave operations unchanged',t=>{const x=setup(t);x.sa.execute(buy);let n=x.a.store.allOperations().length;for(const bad of [{amount:0},{expectedAmount:4500},{reason:' '},{correctedAt:'bad'}])assert.throws(()=>x.sa.execute({...correction,...bad}));assert.equal(x.a.store.allOperations().length,n);x.sa.execute({kind:'REFUND',id:'r',name:'refund',amount:1000,originalId:'buy',destination:'bank',occurredAt:date,status:'PENDING'});n=x.a.store.allOperations().length;assert.throws(()=>x.sa.execute(correction),/ACTIVE_RETURN_LINKS/);assert.equal(x.a.store.allOperations().length,n);});
test('failed audit outbox write rolls back amount and all effects',t=>{const x=setup(t);x.sa.execute(buy);x.a.store.db.exec("CREATE TRIGGER fail_correction BEFORE INSERT ON sync_outbox BEGIN SELECT RAISE(ABORT,'full disk'); END;");assert.throws(()=>x.sa.execute(correction),/full disk/);assert.equal(x.spent(),4400);assert.equal(x.balance(),95600);assert.equal(x.a.store.get('source_records','audit-a'),undefined);});
test('different concurrent corrections conflict while identical ones count once',t=>{const x=setup(t);x.sa.execute(buy);converge(x.a,x.b);x.sa.execute(correction);x.sb.execute({...correction,sourceId:'audit-b',amount:4200});converge(x.a,x.b);assert.ok(x.snapshot().conflicts.some(c=>c.field==='display_amount'));assert.throws(()=>x.spent(),/UNRESOLVED_CONFLICT/);assert.throws(()=>x.sa.execute({...correction,expectedAmount:4000,amount:3900,sourceId:'c'}),/UNRESOLVED_CONFLICT/);});
test('equal concurrent corrections and independent note edit merge safely',t=>{const x=setup(t);x.sa.execute(buy);converge(x.a,x.b);x.sa.execute(correction);x.sb.execute({...correction,sourceId:'audit-b'});x.b.service.execute([patch('transactions','buy','note','new note')]);converge(x.a,x.b);assert.deepEqual(x.snapshot().conflicts,[]);assert.equal(x.spent(),4000);assert.equal(x.balance(),96000);assert.equal(x.a.store.get('transactions','buy')?.fields.note,'new note');});
test('concurrent refund cannot overdraw corrected original amount',t=>{const x=setup(t);x.sa.execute(buy);converge(x.a,x.b);x.sa.execute({...correction,amount:1000});x.sb.execute({kind:'REFUND',id:'r',name:'refund',amount:2000,originalId:'buy',destination:'bank',occurredAt:date});converge(x.a,x.b);assert.ok(x.snapshot().conflicts.some(c=>c.field==='$accounting'));assert.throws(()=>x.balance(),/UNRESOLVED_CONFLICT/);});
test('no-op correction adds no duplicate audit evidence',t=>{const x=setup(t);x.sa.execute(buy);const n=x.a.store.allOperations().length;assert.deepEqual(x.sa.execute({...correction,amount:4400}),[]);assert.equal(x.a.store.allOperations().length,n);});
