import test from 'node:test';
import assert from 'node:assert/strict';
import {pair,converge,patch} from './helpers.ts';
import {BusinessAccountingService} from '../packages/accounting/business.ts';
import {settlementConflictIds} from '../packages/accounting/resolution.ts';
import {project} from '../packages/sync/projection.ts';
import {accountBalance,consumptionInPeriod,unresolvedMovements} from '../packages/analytics/index.ts';
import type {Purchase} from '../packages/domain/accounting.ts';
const time='2026-09-20T00:00:00Z';
const event:Purchase={kind:'PURCHASE',id:'p',name:'Demo',amount:4400,payer:'bank',occurredAt:time};
function setup(t:Parameters<typeof pair>[0]) {
 const x=pair(t),a=new BusinessAccountingService(x.a.store,'a'),b=new BusinessAccountingService(x.b.store,'b');
 for(const [id,type] of [['bank','ASSET'],['credit','LIABILITY']] as const)a.execute({kind:'CREATE_ACCOUNT',id,name:id,accountType:type,openingBalance:type==='ASSET'?100000:0,openingBalanceAt:'2026-09-01T00:00:00Z'});
 a.execute({...event,status:'PENDING',source:{id:'evidence',sourceType:'SCREENSHOT',platform:'TEST',rawPayload:'original'}});converge(x.a,x.b);
 return {...x,sa:a,sb:b,ids:()=>settlementConflictIds(project(x.a.store.allOperations()),'p')};
}
function assertBoth(x:ReturnType<typeof setup>,bank:number,credit:number,spent:number){for(const d of [x.a,x.b]){const s=project(d.store.allOperations());assert.deepEqual(d.store.conflicts(),[]);assert.equal(accountBalance(s,'bank','2026-10-01T00:00:00Z').balance,bank);assert.equal(accountBalance(s,'credit','2026-10-01T00:00:00Z').balance,credit);assert.equal(consumptionInPeriod(s,'2026-09-01T00:00:00Z','2026-10-01T00:00:00Z'),spent);}}
test('resolve success versus failure to success and propagate without double posting',t=>{const x=setup(t);x.sa.execute({kind:'SET_STATUS',transactionId:'p',status:'SUCCESS',settlement:event});x.sb.execute({kind:'SET_STATUS',transactionId:'p',status:'FAILED'});converge(x.a,x.b);x.sa.execute({kind:'RESOLVE_SETTLEMENT',transactionId:'p',status:'SUCCESS',settlement:event,expectedOperationIds:x.ids()});converge(x.a,x.b);assertBoth(x,95600,0,4400);assert.equal(x.a.store.get('source_records','evidence')?.fields.raw_payload,'original');});
test('resolve competing bank/credit interpretations to credit atomically',t=>{const x=setup(t);x.sa.execute({kind:'SET_STATUS',transactionId:'p',status:'SUCCESS',settlement:event});x.sb.execute({kind:'SET_STATUS',transactionId:'p',status:'SUCCESS',settlement:{...event,payer:'credit'}});converge(x.a,x.b);x.sa.execute({kind:'RESOLVE_SETTLEMENT',transactionId:'p',status:'SUCCESS',settlement:{...event,payer:'credit'},expectedOperationIds:x.ids()});converge(x.a,x.b);assertBoth(x,100000,4400,4400);});
test('choosing sponsored payment neutralizes rejected owned movement and keeps source',t=>{const x=setup(t);const sponsored:Purchase={...event,payer:null,funding:'EXTERNAL_SPONSOR'};x.sa.execute({kind:'SET_STATUS',transactionId:'p',status:'SUCCESS',settlement:event});x.sb.execute({kind:'SET_STATUS',transactionId:'p',status:'SUCCESS',settlement:sponsored});converge(x.a,x.b);x.sa.execute({kind:'RESOLVE_SETTLEMENT',transactionId:'p',status:'SUCCESS',settlement:sponsored,expectedOperationIds:x.ids()});converge(x.a,x.b);assertBoth(x,100000,0,4400);assert.equal(unresolvedMovements(project(x.a.store.allOperations())).length,0);x.sa.execute({kind:'REFUND',id:'r',name:'refund',amount:4400,originalId:'p',destination:null,occurredAt:time});converge(x.a,x.b);assertBoth(x,100000,0,0);});
test('choosing failed removes all effective balances and consumption but retains audit',t=>{const x=setup(t);x.sa.execute({kind:'SET_STATUS',transactionId:'p',status:'SUCCESS',settlement:event});x.sb.execute({kind:'SET_STATUS',transactionId:'p',status:'FAILED'});converge(x.a,x.b);const n=x.a.store.allOperations().length;x.sa.execute({kind:'RESOLVE_SETTLEMENT',transactionId:'p',status:'FAILED',expectedOperationIds:x.ids()});converge(x.a,x.b);assertBoth(x,100000,0,0);assert.ok(x.a.store.allOperations().length>n);assert.ok(x.a.store.get('balance_movements','p:movement:0'));});
test('stale conflict selection is rejected before any writes',t=>{const x=setup(t);x.sa.execute({kind:'SET_STATUS',transactionId:'p',status:'SUCCESS',settlement:event});x.sb.execute({kind:'SET_STATUS',transactionId:'p',status:'FAILED'});converge(x.a,x.b);const n=x.a.store.allOperations().length;assert.throws(()=>x.sa.execute({kind:'RESOLVE_SETTLEMENT',transactionId:'p',status:'SUCCESS',settlement:event,expectedOperationIds:[]}),/STALE_CONFLICT/);assert.equal(x.a.store.allOperations().length,n);});
test('outbox failure rolls back the entire settlement resolution',t=>{const x=setup(t);x.sa.execute({kind:'SET_STATUS',transactionId:'p',status:'SUCCESS',settlement:event});x.sb.execute({kind:'SET_STATUS',transactionId:'p',status:'FAILED'});converge(x.a,x.b);const before=x.a.store.conflicts();x.a.store.db.exec("CREATE TRIGGER fail_resolution BEFORE INSERT ON sync_outbox BEGIN SELECT RAISE(ABORT,'disk fault'); END;");assert.throws(()=>x.sa.execute({kind:'RESOLVE_SETTLEMENT',transactionId:'p',status:'FAILED',expectedOperationIds:x.ids()}),/disk fault/);assert.deepEqual(x.a.store.conflicts(),before);});
test('two different concurrent resolutions recreate a conflict rather than overriding',t=>{const x=setup(t);x.sa.execute({kind:'SET_STATUS',transactionId:'p',status:'SUCCESS',settlement:event});x.sb.execute({kind:'SET_STATUS',transactionId:'p',status:'FAILED'});converge(x.a,x.b);const ids=x.ids();x.sa.execute({kind:'RESOLVE_SETTLEMENT',transactionId:'p',status:'SUCCESS',settlement:event,expectedOperationIds:ids});x.sb.execute({kind:'RESOLVE_SETTLEMENT',transactionId:'p',status:'FAILED',expectedOperationIds:ids});converge(x.a,x.b);assert.ok(x.a.store.conflicts().length);assert.deepEqual(x.a.store.conflicts(),x.b.store.conflicts());});
test('unrelated notes survive whole-settlement resolution',t=>{const x=setup(t);x.sa.execute({kind:'SET_STATUS',transactionId:'p',status:'SUCCESS',settlement:event});x.sb.execute({kind:'SET_STATUS',transactionId:'p',status:'FAILED'});converge(x.a,x.b);x.a.service.execute([patch('transactions','p','note','user note')]);x.sa.execute({kind:'RESOLVE_SETTLEMENT',transactionId:'p',status:'SUCCESS',settlement:event,expectedOperationIds:x.ids()});converge(x.a,x.b);assert.equal(x.b.store.get('transactions','p')?.fields.note,'user note');});

test('deletion concurrent with settlement resolution remains an explicit lifecycle conflict',t=>{const x=setup(t);x.sa.execute({kind:'SET_STATUS',transactionId:'p',status:'SUCCESS',settlement:event});x.sb.execute({kind:'SET_STATUS',transactionId:'p',status:'FAILED'});converge(x.a,x.b);x.sa.execute({kind:'RESOLVE_SETTLEMENT',transactionId:'p',status:'SUCCESS',settlement:event,expectedOperationIds:x.ids()});x.sb.execute({kind:'DELETE_TRANSACTION',transactionId:'p',deletedAt:time});converge(x.a,x.b);assert.ok(x.a.store.conflicts().some(c=>c.field==='$lifecycle'));assert.deepEqual(x.a.store.conflicts(),x.b.store.conflicts());});
