const {chromium}=require('playwright');
const fs=require('fs'),path=require('path'),http=require('http'),assert=require('assert/strict'),crypto=require('crypto');
const root=path.resolve('web-dist');
const server=http.createServer((req,res)=>{const url=decodeURIComponent(req.url.split('?')[0]);let f=url.startsWith('/test-fonts/')?path.join(process.cwd(),'node_modules/@fontsource/noto-sans-sc',url.slice(12)):path.join(root,url);if(f.endsWith('/'))f+='index.html';try{res.setHeader('Content-Type',({'.js':'text/javascript','.css':'text/css','.html':'text/html','.svg':'image/svg+xml','.woff2':'font/woff2','.webmanifest':'application/manifest+json'})[path.extname(f)]||'application/octet-stream');res.end(fs.readFileSync(f));}catch{res.writeHead(404);res.end();}});
const results=[];const ok=s=>{results.push(s);console.log('PASS',s)};
async function db(page){return page.evaluate(()=>new Promise((resolve,reject)=>{const req=indexedDB.open('star-ledger-next-v1');req.onsuccess=()=>{const r=req.result.transaction('ledger').objectStore('ledger').get('main');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);};}));}
async function ready(page){await page.goto('http://127.0.0.1:4173/');await page.locator('.hero-value').waitFor();}
async function nav(page,p){await page.locator(`[data-page=${p}]:visible`).first().click();}
async function newAccount(page,name,amount){await page.locator('[data-action=account]:visible').first().click();const f=page.locator('#account-form');await f.locator('[name=name]').fill(name);await f.locator('[name=balance]').fill(amount);await f.locator('[name=date]').fill('2026-09-01T00:00');await f.locator('[type=submit]').click();await page.locator('dialog').waitFor({state:'hidden'});}
async function newBill(page,kind,name,amount,account,extra={}){await page.locator('[data-action=new]:visible').first().click();await page.locator('#record-kind').selectOption(kind);const f=page.locator('#record-form');await f.locator('[name=name]').fill(name);await f.locator('[name=amount]').fill(amount);await f.locator('[name=date]').fill('2026-09-20T12:00');if(account!==undefined)await f.locator('[name=account]').selectOption(account);for(const[k,v]of Object.entries(extra))await f.locator(`[name=${k}]`).selectOption(v);await f.locator('[type=submit]').click();await page.locator('dialog').waitFor({state:'hidden'});}
async function font(page){if(!fs.existsSync('node_modules/@fontsource/noto-sans-sc/400.css'))return;await page.addStyleTag({content:fs.readFileSync('node_modules/@fontsource/noto-sans-sc/400.css','utf8').replaceAll('./files/','/test-fonts/files/')+'\n:root{font-family:"Noto Sans SC",sans-serif}'});await page.evaluate(()=>document.fonts.ready);}

(async()=>{await new Promise(r=>server.listen(4173,'127.0.0.1',r));const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader'],headless:true});try{const context=await browser.newContext({viewport:{width:480,height:760},timezoneId:'Asia/Shanghai'});const screenshot=await context.newPage();await ready(screenshot);await screenshot.setContent('<html><body style="background:white;color:black;padding:35px;font:24px &quot;Noto Sans SC&quot;,sans-serif"><h2>微信支付</h2><p>支付成功</p><h1 style="font-size:50px">￥44.00</h1><p>收款方 测试商户</p><p>付款方式 银行卡</p><p style="font-size:20px">2026-09-20 12:00:00</p><p>交易单号 202609201234567890</p></body></html>');await font(screenshot);await screenshot.screenshot({path:'tests/fixtures/payment.png'});await screenshot.close();
 await context.route('https://cdn.jsdelivr.net/**',async route=>{const u=new URL(route.request().url());let f;if(u.pathname.includes('tesseract.js@'))f=path.resolve('node_modules/tesseract.js/dist/worker.min.js');else if(u.pathname.includes('tesseract.js-core@'))f=path.resolve('node_modules/tesseract.js-core',u.pathname.split('/').pop());else return route.abort();await route.fulfill({status:200,headers:{'access-control-allow-origin':'*'},contentType:f.endsWith('.wasm')?'application/wasm':'text/javascript',body:fs.readFileSync(f)});});
 await context.route('https://tessdata.projectnaptha.com/**',async route=>{const name=new URL(route.request().url()).pathname.split('/').pop();const lang=name.split('.')[0];await route.fulfill({status:200,headers:{'access-control-allow-origin':'*'},contentType:'application/octet-stream',body:fs.readFileSync(path.resolve('node_modules/@tesseract.js-data',lang,'4.0.0',name))});});
 const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')console.log('CONSOLE',m.text())});await ready(page);const chooser=page.waitForEvent('filechooser');await page.locator('[data-action=capture]').first().click();await(await chooser).setFiles('tests/fixtures/payment.png');await page.locator('#record-form').waitFor({timeout:90000});assert.equal(await page.locator('#record-form [name=amount]').inputValue(),'44.00');const date=await page.locator('#record-form [name=date]').inputValue();assert.match(date,/2026-09-20/);assert.equal(await page.locator('#record-form [name=name]').inputValue(),'测试商户');console.log('PASS Actual Chinese OCR recognizes amount and date from synthetic screenshot');fs.writeFileSync('docs/ocr-validation.json',JSON.stringify({date:new Date().toISOString(),result:'Actual Tesseract Chinese model in browser recognized synthetic payment screenshot amount 44.00 and date 2026-09-20',assets:'Test routed pinned engine/model requests to locally installed identical package assets; live CDN availability not established',errors},null,2));}finally{await browser.close();server.close();}})().catch(e=>{console.error(e);process.exit(1)});
